version: '3.8'

services:
  mlflow_server:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./experiments:/mlflow/experiments
    command: mlflow server --backend-store-uri file:///mlflow/experiments --host 0.0.0.0 --port 5000

  model_api:
    image: ml_project_api:latest
    container_name: model_api
    ports:
      - "8000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - MODEL_NAME=ClassificationModel
      - MODEL_VERSION=6
    depends_on:
      - mlflow_server
    volumes:
      - ./experiments:/app/experiments